### ISSUE TITLE
TypeError cases

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-traceback#52]
From https://github.com/aroberge/friendly/issues/140

- [ ] https://twitter.com/python_tip/status/1349035347833978888  About positional only function arguments.
- [ ] TypeError: vars() argument must have `__dict__` attribute, when using an object with `__slots__`
- [ ] TypeError: 'in <string>' requires string as left operand, not int  (issue https://github.com/aroberge/friendly/issues/148)
- [ ] TypeError: keywords must be strings (issue https://github.com/aroberge/friendly/issues/165)
- [ ] TypeError: there are no type variables left ... (issue https://github.com/aroberge/friendly/issues/184)
- [ ] TypeError: 'builtin_function_or_method' object is not subscriptable  (issue https://github.com/aroberge/friendly/issues/166)
- [ ] TypeError: globals() takes no arguments (1 given) (issue https://github.com/aroberge/friendly/issues/166)
- [ ] TypeError: string indices must be integers (note: might change wording in 3.10; see https://bugs.python.org/issue35077)
- [ ] Traceback (most recent call last):
  File "<friendly-console:2>", line 1, in <module>
    divmod(3, 0j)
TypeError: can't take floor or mod of complex number.

- [ ] >>> 3 % 0j

Traceback (most recent call last):
  File "<friendly-console:3>", line 1, in <module>
    3 % 0j
TypeError: can't mod complex numbers.

**Comment by aroberge** [comment]
- [ ] See also https://bugs.python.org/issue44110
